config/routes.rb
UserStudy::Application.routes.draw do
  resources :events

  config_vars

  resources :signups do
    member { post :remind }
  end
  resources :timeslots
  

  root :to => "signups#new"

end

app/models/config_var.rb
# Configuration flags that are global to the installation.
class ConfigVar < ActiveRecord::Base
  config_vars_model

  # Add your extensions to the ConfigVar class here.
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :time_slots, :dependent => :destroy
end

app/models/signup.rb
class Signup < ActiveRecord::Base
  belongs_to :timeslot
  
  validates_each :timeslot do |record, attr, value|
    if record.timeslot.openings_left <= 0
      record.errors.add attr, "No openings left for this time"
    end
  end
  
  validates_uniqueness_of :name
  validates_uniqueness_of :email
  validates_presence_of :name
  validates_presence_of :email
  validates_format_of :email,
                      :with => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  has_many :signups, :dependent => :destroy
  belongs_to :event
  
  def self.open_timeslots
    Timeslot.all.select { |t| t.openings_left > 0 }.map { |t| [t.name, t.id] }
  end

  def openings_left
    openings - signups.length    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/config_vars_controller.rb
# Viewing and changing configuration variables.
class ConfigVarsController < ApplicationController
  config_vars_controller

  config_vars_auth
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  config_vars_auth :only => :index
  
  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all(:include => :timeslot, :order => "timeslots.name")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @signups }
    end
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
    @signup = Signup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @signup }
    end
  end

  # GET /signups/new
  # GET /signups/new.json
  def new
    @signup = Signup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @signup }
    end
  end

  # GET /signups/1/edit
  def edit
    @signup = Signup.find(params[:id])
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(params[:signup])

    respond_to do |format|
      if @signup.save
        flash[:notice] = 'Signup was successfully created.'
        Emails.confirmation(@signup).deliver
        format.html { redirect_to(@signup) }
        format.json { render :json => @signup, :status => :created, :location => @signup }
      else
        format.html { render :action => "new" }
        format.json { render :json => @signup.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def remind
    @signup = Signup.find(params[:id])
    Emails.reminder(@signup).deliver
    flash[:notice] = "Reminder for #{@signup.email} delivered"
    redirect_to signups_path
  end

  # PUT /signups/1
  # PUT /signups/1.json
  def update
    @signup = Signup.find(params[:id])

    respond_to do |format|
      if @signup.update_attributes(params[:signup])
        flash[:notice] = 'Signup was successfully updated.'
        format.html { redirect_to(@signup) }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @signup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup = Signup.find(params[:id])
    @signup.destroy

    respond_to do |format|
      format.html { redirect_to(signups_url) }
      format.json { head :ok }
    end
  end  
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  config_vars_auth

  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @timeslots }
    end
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @timeslot }
    end
  end

  # GET /timeslots/new
  # GET /timeslots/new.json
  def new
    @timeslot = Timeslot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @timeslot }
    end
  end

  # GET /timeslots/1/edit
  def edit
    @timeslot = Timeslot.find(params[:id])
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(params[:timeslot])

    respond_to do |format|
      if @timeslot.save
        flash[:notice] = 'Timeslot was successfully created.'
        format.html { redirect_to(@timeslot) }
        format.json { render :json => @timeslot, :status => :created, :location => @timeslot }
      else
        format.html { render :action => "new" }
        format.json { render :json => @timeslot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /timeslots/1
  # PUT /timeslots/1.json
  def update
    @timeslot = Timeslot.find(params[:id])

    respond_to do |format|
      if @timeslot.update_attributes(params[:timeslot])
        flash[:notice] = 'Timeslot was successfully updated.'
        format.html { redirect_to(@timeslot) }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @timeslot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy

    respond_to do |format|
      format.html { redirect_to(timeslots_url) }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/config_vars/edit.html.erb
<h2>Editing Configuration Variable</h2>

<%= form_for(@config_var, :url => config_var_path(@config_var),
                          :html => { :method => :put }) do |f| %>
  <% if @config_var.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@config_var.errors.count, "error") %> prohibited this config_var from being saved:</h3>

      <ul>
      <% @config_var.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', config_vars_path %>

app/views/config_vars/index.html.erb
<h2>Set Configuration Variables</h2>

<table class="configuration_variables">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Value</th>
    <th>Default Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @config_vars.each do |config_var| %>
  <tr>
    <td><%= config_var.name %></td>
    <td>
      <%= config_var.descriptor ? config_var.descriptor.value_type :
              'undefined' %>
    </td>
    <td><%= config_var.value %></td>
    <td>
      <%= config_var.descriptor ? config_var.descriptor.default_value :
              'undefined' %>
    </td>
    <td><%= link_to 'Edit', edit_config_var_path(config_var) %></td>
    <td><%= link_to 'Reset to default', config_var, :method => :delete %></td>
  </tr>
<% end %>
</table>

<h2>Available Configuration Variables</h2>

<table class="configuration_variables">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Default Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @default_vars.each do |name, descriptor| %>
  <tr>
    <td><%= name %></td>
    <td><%= descriptor.value_type %></td>
    <td><%= descriptor.default_value %></td>
    <td><%= link_to 'Edit', edit_config_var_path(:name => name) %></td>
  </tr>
<% end %>
</table>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :header %><br />
    <%= f.text_field :header %>
  </div>
  <div class="field">
    <%= f.label :event_title %><br />
    <%= f.text_field :event_title %>
  </div>
  <div class="field">
    <%= f.label :requirement %><br />
    <%= f.text_field :requirement %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Header</th>
    <th>Event title</th>
    <th>Requirement</th>
    <th>Location</th>
    <th>Duration</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.header %></td>
    <td><%= event.event_title %></td>
    <td><%= event.requirement %></td>
    <td><%= event.location %></td>
    <td><%= event.duration %></td>
    <td><%= event.description %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Header:</b>
  <%= @event.header %>
</p>

<p>
  <b>Event title:</b>
  <%= @event.event_title %>
</p>

<p>
  <b>Requirement:</b>
  <%= @event.requirement %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Duration:</b>
  <%= @event.duration %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/config_vars.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= config_vars_app_name %> Vars</title>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <h1><%= config_vars_app_name %> Configuration Vars</h1>
<%= yield %>
  </body>
</html>

app/views/layouts/signups.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Two AMC Gold movie tickets for 45min</title>
  <%= stylesheet_link_tag 'scaffold' %>
	<%= javascript_include_tag :defaults %>
</head>
<body>
	<header>
	  <h1>User Study Signup</h1>
	</header>
  <article>
    <%= yield %>
  </article>
  <footer></footer>
</body>
</html>

app/views/layouts/timeslots.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timeslots: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= javascript_include_tag :defaults %>
</head>
<body>
  <article>
    <p style="color: green"><%= flash[:notice] %></p>
    <%= yield %>
  </article>
</body>
</html>

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :required => true, :placeholder => 'John Doe',
                            :autofocus => true %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email, :required => true,
                              :placeholder => 'john@gmail.com' %>
  </p>
  <p>
    <%= f.label :timeslot_id, 'Choose a time slot' %><br />
    <% open_timeslots = Timeslot.open_timeslots %>
    <% if open_timeslots.empty? %>
    <p>All time slots are taken. Thank you for your interest!</p>
    <% else %>
    <%= f.select :timeslot_id, open_timeslots %>
    <% end %>
  </p>
  <p>
    To speed up the process, the <a href="http://bit.ly/eObOzC" target="_blank">consent form</a> 
    (a standard form for user studies) that you will need to sign during the study 
    is included here for your reference.
  </p>
  <div class = "uiButton">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<h1>Listing signups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Timeslot</th>
  </tr>
<% @signups.each do |signup| %>
  <tr>
    <td><%=h signup.name %></td>
    <td><%=h signup.email %></td>
    <td><%=h signup.timeslot.name %></td>
    <td><%= link_to 'Show', signup %></td>
    <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
    <td><%= link_to 'Destroy', signup, :confirm => 'Are you sure?', :method => :delete %></td>
		<td><%= link_to 'Remind', remind_signup_path(signup), :method => :post %></td>
  </tr>
<% end %>
</table>
<p>Total = <%= @signups.length%></p>
<br />

<%= link_to 'New signup', new_signup_path %>

app/views/signups/new.html.erb
<section>
<p><strong>Two AMC Gold movie tickets for 45min of your time.</strong></p>

<%= render 'form' %>
</section>
<section>
  <h4>Study Title</h4>
  <p>
    New User Interface for Online Language Exchange
  </p>
  <h4>Requirement</h4>
  <p>
    To participate in the study, you must be:
    <ul>
      <li>over 18 years old</li>
      <li>
        a native <a href="http://en.wikipedia.org/wiki/Standard_Chinese">Mandarin Chinese</a> 
        speaker
      </li>
      <li>able to input <a href="http://en.wikipedia.org/wiki/Simplified_Chinese_characters">
        simplified Chinese characters</a> on a computer using a Pingyin input method.
    </ul>
  </p>
  <h4>Location & Duration</h4>
  <p>
    Study takes place at <strong><a href="http://whereis.mit.edu/?go=32" target="_blank">Stata Center</a> 
    <a href="https://www.csail.mit.edu/mrbs/room-desc.php?room=1">32-261</a> or 
    <a href="https://www.csail.mit.edu/mrbs/room-desc.php?room=14">32-262</a></strong>
    (depending on your time slot), and lasts about 45min.
  </p>
  <h4>Description</h4>
  <p>
    This user study is conducted by the Multimodal Understanding Group at MIT CSAIL to 
    evaluate the effectiveness of a new user interface for online language exchange.  
  </p>
</section>

app/views/signups/remind.html.erb
Reminder is successfully sent!
<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<section>
<p style="color: green"><%= flash[:notice] %></p>
Thank you for signing up for my user study. This is your information. A confirmation email is also sent to your email box.

<p>
  <b>Name:</b>
  <%=h @signup.name %>
</p>

<p>
  <b>Email:</b>
  <%=h @signup.email %>
</p>

<p>
  <b>Time slot:</b>
  <%=h @signup.timeslot.name %>
</p>
</section>

app/views/timeslots/_form.html.erb
<%= form_for(@timeslot) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :placeholder => 'Monday 3/21, 5pm' %>
  </p>
  <p>
    <%= f.label :openings %><br />
    <%= f.number_field :openings, :min => 1, :placeholder => '1',
                       :autofocus => true %>
  </p>
  <p>
    <%= f.label :event %><br />
    <%= f.number_field :event %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing timeslot</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<h1>Listing timeslots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Openings</th>
		<th>Openings left</th>
  </tr>

<% @timeslots.each do |timeslot| %>
  <tr>
    <td><%=h timeslot.name %></td>
    <td><%=h timeslot.openings %></td>
    <td><%=h timeslot.openings_left %></td>
    <td><%= link_to 'Show', timeslot %></td>
    <td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
    <td><%= link_to 'Destroy', timeslot, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New timeslot', new_timeslot_path %>

app/views/timeslots/new.html.erb
<h1>New timeslot</h1>

<%= render 'form' %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<p>
  <b>Name:</b>
  <%=h @timeslot.name %>
</p>

<p>
  <b>Openings:</b>
  <%=h @timeslot.openings %>
</p>


<%= link_to 'Edit', edit_timeslot_path(@timeslot) %> |
<%= link_to 'Back', timeslots_path %>